create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text,
  age integer,
  location text,
  email text not null,
  phone text,
  height text,
  weight text,
  body_type text,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

create policy "Allow public booking inserts"
on public.leads
for insert
to anon
with check (true);